#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace infoT2.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_info_T2_NOITE")]
	public partial class MeuBDNoCSharpDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblCategoria(tblCategoria instance);
    partial void UpdatetblCategoria(tblCategoria instance);
    partial void DeletetblCategoria(tblCategoria instance);
    partial void InserttblProduto(tblProduto instance);
    partial void UpdatetblProduto(tblProduto instance);
    partial void DeletetblProduto(tblProduto instance);
    #endregion
		
		public MeuBDNoCSharpDataContext() : 
				base(global::infoT2.DAL.Properties.Settings.Default.db_info_T2_NOITEConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MeuBDNoCSharpDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MeuBDNoCSharpDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MeuBDNoCSharpDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MeuBDNoCSharpDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblCategoria> tblCategorias
		{
			get
			{
				return this.GetTable<tblCategoria>();
			}
		}
		
		public System.Data.Linq.Table<tblProduto> tblProdutos
		{
			get
			{
				return this.GetTable<tblProduto>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_categoria")]
	public partial class tblCategoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodigoCategoria;
		
		private string _NomeCategoria;
		
		private EntitySet<tblProduto> _tblProdutos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoCategoriaChanging(int value);
    partial void OnCodigoCategoriaChanged();
    partial void OnNomeCategoriaChanging(string value);
    partial void OnNomeCategoriaChanged();
    #endregion
		
		public tblCategoria()
		{
			this._tblProdutos = new EntitySet<tblProduto>(new Action<tblProduto>(this.attach_tblProdutos), new Action<tblProduto>(this.detach_tblProdutos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_Categoria", Storage="_CodigoCategoria", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodigoCategoria
		{
			get
			{
				return this._CodigoCategoria;
			}
			set
			{
				if ((this._CodigoCategoria != value))
				{
					this.OnCodigoCategoriaChanging(value);
					this.SendPropertyChanging();
					this._CodigoCategoria = value;
					this.SendPropertyChanged("CodigoCategoria");
					this.OnCodigoCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="descri_Categoria", Storage="_NomeCategoria", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NomeCategoria
		{
			get
			{
				return this._NomeCategoria;
			}
			set
			{
				if ((this._NomeCategoria != value))
				{
					this.OnNomeCategoriaChanging(value);
					this.SendPropertyChanging();
					this._NomeCategoria = value;
					this.SendPropertyChanged("NomeCategoria");
					this.OnNomeCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblCategoria_tblProduto", Storage="_tblProdutos", ThisKey="CodigoCategoria", OtherKey="FKCodigoCategoria")]
		public EntitySet<tblProduto> tblProdutos
		{
			get
			{
				return this._tblProdutos;
			}
			set
			{
				this._tblProdutos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblProdutos(tblProduto entity)
		{
			this.SendPropertyChanging();
			entity.tblCategoria = this;
		}
		
		private void detach_tblProdutos(tblProduto entity)
		{
			this.SendPropertyChanging();
			entity.tblCategoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Produto")]
	public partial class tblProduto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodigoProduto;
		
		private string _NomeProduto;
		
		private decimal _ValorProduto;
		
		private int _CodigoCategoria;
		
		private EntityRef<tblCategoria> _tblCategoria;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoProdutoChanging(int value);
    partial void OnCodigoProdutoChanged();
    partial void OnNomeProdutoChanging(string value);
    partial void OnNomeProdutoChanged();
    partial void OnValorProdutoChanging(decimal value);
    partial void OnValorProdutoChanged();
    partial void OnFKCodigoCategoriaChanging(int value);
    partial void OnFKCodigoCategoriaChanged();
    #endregion
		
		public tblProduto()
		{
			this._tblCategoria = default(EntityRef<tblCategoria>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_Produto", Storage="_CodigoProduto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodigoProduto
		{
			get
			{
				return this._CodigoProduto;
			}
			set
			{
				if ((this._CodigoProduto != value))
				{
					this.OnCodigoProdutoChanging(value);
					this.SendPropertyChanging();
					this._CodigoProduto = value;
					this.SendPropertyChanged("CodigoProduto");
					this.OnCodigoProdutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="descri_Produto", Storage="_NomeProduto", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NomeProduto
		{
			get
			{
				return this._NomeProduto;
			}
			set
			{
				if ((this._NomeProduto != value))
				{
					this.OnNomeProdutoChanging(value);
					this.SendPropertyChanging();
					this._NomeProduto = value;
					this.SendPropertyChanged("NomeProduto");
					this.OnNomeProdutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="valor", Storage="_ValorProduto", DbType="Decimal(18,0) NOT NULL")]
		public decimal ValorProduto
		{
			get
			{
				return this._ValorProduto;
			}
			set
			{
				if ((this._ValorProduto != value))
				{
					this.OnValorProdutoChanging(value);
					this.SendPropertyChanging();
					this._ValorProduto = value;
					this.SendPropertyChanged("ValorProduto");
					this.OnValorProdutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_Categoria", Storage="_CodigoCategoria", DbType="Int NOT NULL")]
		public int FKCodigoCategoria
		{
			get
			{
				return this._CodigoCategoria;
			}
			set
			{
				if ((this._CodigoCategoria != value))
				{
					this.OnFKCodigoCategoriaChanging(value);
					this.SendPropertyChanging();
					this._CodigoCategoria = value;
					this.SendPropertyChanged("FKCodigoCategoria");
					this.OnFKCodigoCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblCategoria_tblProduto", Storage="_tblCategoria", ThisKey="FKCodigoCategoria", OtherKey="CodigoCategoria", IsForeignKey=true)]
		public tblCategoria tblCategoria
		{
			get
			{
				return this._tblCategoria.Entity;
			}
			set
			{
				tblCategoria previousValue = this._tblCategoria.Entity;
				if (((previousValue != value) 
							|| (this._tblCategoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblCategoria.Entity = null;
						previousValue.tblProdutos.Remove(this);
					}
					this._tblCategoria.Entity = value;
					if ((value != null))
					{
						value.tblProdutos.Add(this);
						this._CodigoCategoria = value.CodigoCategoria;
					}
					else
					{
						this._CodigoCategoria = default(int);
					}
					this.SendPropertyChanged("tblCategoria");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
