#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace info.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_info_T1_noite")]
	public partial class MeuBDNoCSharpDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblProduto(tblProduto instance);
    partial void UpdatetblProduto(tblProduto instance);
    partial void DeletetblProduto(tblProduto instance);
    partial void InserttblCategoria(tblCategoria instance);
    partial void UpdatetblCategoria(tblCategoria instance);
    partial void DeletetblCategoria(tblCategoria instance);
    partial void Inserttblpessoa(tblpessoa instance);
    partial void Updatetblpessoa(tblpessoa instance);
    partial void Deletetblpessoa(tblpessoa instance);
    partial void InserttblPessoaFisica(tblPessoaFisica instance);
    partial void UpdatetblPessoaFisica(tblPessoaFisica instance);
    partial void DeletetblPessoaFisica(tblPessoaFisica instance);
    partial void InserttblPessoaJuridica(tblPessoaJuridica instance);
    partial void UpdatetblPessoaJuridica(tblPessoaJuridica instance);
    partial void DeletetblPessoaJuridica(tblPessoaJuridica instance);
    partial void InserttblUsuario(tblUsuario instance);
    partial void UpdatetblUsuario(tblUsuario instance);
    partial void DeletetblUsuario(tblUsuario instance);
    partial void Inserttb_venda(tb_venda instance);
    partial void Updatetb_venda(tb_venda instance);
    partial void Deletetb_venda(tb_venda instance);
    partial void Inserttb_itens_venda(tb_itens_venda instance);
    partial void Updatetb_itens_venda(tb_itens_venda instance);
    partial void Deletetb_itens_venda(tb_itens_venda instance);
    partial void Inserttb_status_pagamento(tb_status_pagamento instance);
    partial void Updatetb_status_pagamento(tb_status_pagamento instance);
    partial void Deletetb_status_pagamento(tb_status_pagamento instance);
    partial void Inserttb_contas_receber(tb_contas_receber instance);
    partial void Updatetb_contas_receber(tb_contas_receber instance);
    partial void Deletetb_contas_receber(tb_contas_receber instance);
    #endregion
		
		public MeuBDNoCSharpDataContext() : 
				base(global::info.DAL.Properties.Settings.Default.db_info_T1_noiteConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MeuBDNoCSharpDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MeuBDNoCSharpDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MeuBDNoCSharpDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MeuBDNoCSharpDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblProduto> tblProdutos
		{
			get
			{
				return this.GetTable<tblProduto>();
			}
		}
		
		public System.Data.Linq.Table<tblCategoria> tblCategorias
		{
			get
			{
				return this.GetTable<tblCategoria>();
			}
		}
		
		public System.Data.Linq.Table<tblpessoa> tblpessoas
		{
			get
			{
				return this.GetTable<tblpessoa>();
			}
		}
		
		public System.Data.Linq.Table<tblPessoaFisica> tblPessoaFisicas
		{
			get
			{
				return this.GetTable<tblPessoaFisica>();
			}
		}
		
		public System.Data.Linq.Table<tblPessoaJuridica> tblPessoaJuridicas
		{
			get
			{
				return this.GetTable<tblPessoaJuridica>();
			}
		}
		
		public System.Data.Linq.Table<tblUsuario> tblUsuarios
		{
			get
			{
				return this.GetTable<tblUsuario>();
			}
		}
		
		public System.Data.Linq.Table<tb_venda> tb_vendas
		{
			get
			{
				return this.GetTable<tb_venda>();
			}
		}
		
		public System.Data.Linq.Table<tb_itens_venda> tb_itens_vendas
		{
			get
			{
				return this.GetTable<tb_itens_venda>();
			}
		}
		
		public System.Data.Linq.Table<tb_status_pagamento> tb_status_pagamentos
		{
			get
			{
				return this.GetTable<tb_status_pagamento>();
			}
		}
		
		public System.Data.Linq.Table<tb_contas_receber> tb_contas_recebers
		{
			get
			{
				return this.GetTable<tb_contas_receber>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_produto")]
	public partial class tblProduto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodigoProduto;
		
		private string _NomeProduto;
		
		private decimal _valorProduto;
		
		private int _FKCodigoCategoria;
		
		private EntitySet<tb_itens_venda> _tb_itens_vendas;
		
		private EntityRef<tblCategoria> _tblCategoria;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoProdutoChanging(int value);
    partial void OnCodigoProdutoChanged();
    partial void OnNomeProdutoChanging(string value);
    partial void OnNomeProdutoChanged();
    partial void OnvalorProdutoChanging(decimal value);
    partial void OnvalorProdutoChanged();
    partial void OnFKCodigoCategoriaChanging(int value);
    partial void OnFKCodigoCategoriaChanged();
    #endregion
		
		public tblProduto()
		{
			this._tb_itens_vendas = new EntitySet<tb_itens_venda>(new Action<tb_itens_venda>(this.attach_tb_itens_vendas), new Action<tb_itens_venda>(this.detach_tb_itens_vendas));
			this._tblCategoria = default(EntityRef<tblCategoria>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_produto", Storage="_CodigoProduto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodigoProduto
		{
			get
			{
				return this._CodigoProduto;
			}
			set
			{
				if ((this._CodigoProduto != value))
				{
					this.OnCodigoProdutoChanging(value);
					this.SendPropertyChanging();
					this._CodigoProduto = value;
					this.SendPropertyChanged("CodigoProduto");
					this.OnCodigoProdutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="descri_Produto", Storage="_NomeProduto", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NomeProduto
		{
			get
			{
				return this._NomeProduto;
			}
			set
			{
				if ((this._NomeProduto != value))
				{
					this.OnNomeProdutoChanging(value);
					this.SendPropertyChanging();
					this._NomeProduto = value;
					this.SendPropertyChanged("NomeProduto");
					this.OnNomeProdutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="valor", Storage="_valorProduto", DbType="Decimal(18,0) NOT NULL")]
		public decimal valorProduto
		{
			get
			{
				return this._valorProduto;
			}
			set
			{
				if ((this._valorProduto != value))
				{
					this.OnvalorProdutoChanging(value);
					this.SendPropertyChanging();
					this._valorProduto = value;
					this.SendPropertyChanged("valorProduto");
					this.OnvalorProdutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_categoria", Storage="_FKCodigoCategoria", DbType="Int NOT NULL")]
		public int FKCodigoCategoria
		{
			get
			{
				return this._FKCodigoCategoria;
			}
			set
			{
				if ((this._FKCodigoCategoria != value))
				{
					this.OnFKCodigoCategoriaChanging(value);
					this.SendPropertyChanging();
					this._FKCodigoCategoria = value;
					this.SendPropertyChanged("FKCodigoCategoria");
					this.OnFKCodigoCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblProduto_tb_itens_venda", Storage="_tb_itens_vendas", ThisKey="CodigoProduto", OtherKey="FKCodigoproduto")]
		public EntitySet<tb_itens_venda> tb_itens_vendas
		{
			get
			{
				return this._tb_itens_vendas;
			}
			set
			{
				this._tb_itens_vendas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblCategoria_tblProduto", Storage="_tblCategoria", ThisKey="FKCodigoCategoria", OtherKey="codigoCategoria", IsForeignKey=true)]
		public tblCategoria tblCategoria
		{
			get
			{
				return this._tblCategoria.Entity;
			}
			set
			{
				tblCategoria previousValue = this._tblCategoria.Entity;
				if (((previousValue != value) 
							|| (this._tblCategoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblCategoria.Entity = null;
						previousValue.tblProdutos.Remove(this);
					}
					this._tblCategoria.Entity = value;
					if ((value != null))
					{
						value.tblProdutos.Add(this);
						this._FKCodigoCategoria = value.codigoCategoria;
					}
					else
					{
						this._FKCodigoCategoria = default(int);
					}
					this.SendPropertyChanged("tblCategoria");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_itens_vendas(tb_itens_venda entity)
		{
			this.SendPropertyChanging();
			entity.tblProduto = this;
		}
		
		private void detach_tb_itens_vendas(tb_itens_venda entity)
		{
			this.SendPropertyChanging();
			entity.tblProduto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_categoria")]
	public partial class tblCategoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _codigoCategoria;
		
		private string _NomeCategoria;
		
		private EntitySet<tblProduto> _tblProdutos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncodigoCategoriaChanging(int value);
    partial void OncodigoCategoriaChanged();
    partial void OnNomeCategoriaChanging(string value);
    partial void OnNomeCategoriaChanged();
    #endregion
		
		public tblCategoria()
		{
			this._tblProdutos = new EntitySet<tblProduto>(new Action<tblProduto>(this.attach_tblProdutos), new Action<tblProduto>(this.detach_tblProdutos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_Categoria", Storage="_codigoCategoria", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int codigoCategoria
		{
			get
			{
				return this._codigoCategoria;
			}
			set
			{
				if ((this._codigoCategoria != value))
				{
					this.OncodigoCategoriaChanging(value);
					this.SendPropertyChanging();
					this._codigoCategoria = value;
					this.SendPropertyChanged("codigoCategoria");
					this.OncodigoCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="descri_categoria", Storage="_NomeCategoria", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NomeCategoria
		{
			get
			{
				return this._NomeCategoria;
			}
			set
			{
				if ((this._NomeCategoria != value))
				{
					this.OnNomeCategoriaChanging(value);
					this.SendPropertyChanging();
					this._NomeCategoria = value;
					this.SendPropertyChanged("NomeCategoria");
					this.OnNomeCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblCategoria_tblProduto", Storage="_tblProdutos", ThisKey="codigoCategoria", OtherKey="FKCodigoCategoria")]
		public EntitySet<tblProduto> tblProdutos
		{
			get
			{
				return this._tblProdutos;
			}
			set
			{
				this._tblProdutos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblProdutos(tblProduto entity)
		{
			this.SendPropertyChanging();
			entity.tblCategoria = this;
		}
		
		private void detach_tblProdutos(tblProduto entity)
		{
			this.SendPropertyChanging();
			entity.tblCategoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_pessoa")]
	public partial class tblpessoa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Codigopessoa;
		
		private string _NomePessoa;
		
		private string _TelefonePessoa;
		
		private string _EmailPessoa;
		
		private EntityRef<tblPessoaFisica> _tblPessoaFisica;
		
		private EntityRef<tblPessoaJuridica> _tblPessoaJuridica;
		
		private EntityRef<tblUsuario> _tblUsuario;
		
		private EntitySet<tb_venda> _tb_vendas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigopessoaChanging(int value);
    partial void OnCodigopessoaChanged();
    partial void OnNomePessoaChanging(string value);
    partial void OnNomePessoaChanged();
    partial void OnTelefonePessoaChanging(string value);
    partial void OnTelefonePessoaChanged();
    partial void OnEmailPessoaChanging(string value);
    partial void OnEmailPessoaChanged();
    #endregion
		
		public tblpessoa()
		{
			this._tblPessoaFisica = default(EntityRef<tblPessoaFisica>);
			this._tblPessoaJuridica = default(EntityRef<tblPessoaJuridica>);
			this._tblUsuario = default(EntityRef<tblUsuario>);
			this._tb_vendas = new EntitySet<tb_venda>(new Action<tb_venda>(this.attach_tb_vendas), new Action<tb_venda>(this.detach_tb_vendas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_pessoa", Storage="_Codigopessoa", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Codigopessoa
		{
			get
			{
				return this._Codigopessoa;
			}
			set
			{
				if ((this._Codigopessoa != value))
				{
					this.OnCodigopessoaChanging(value);
					this.SendPropertyChanging();
					this._Codigopessoa = value;
					this.SendPropertyChanged("Codigopessoa");
					this.OnCodigopessoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="nome", Storage="_NomePessoa", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string NomePessoa
		{
			get
			{
				return this._NomePessoa;
			}
			set
			{
				if ((this._NomePessoa != value))
				{
					this.OnNomePessoaChanging(value);
					this.SendPropertyChanging();
					this._NomePessoa = value;
					this.SendPropertyChanged("NomePessoa");
					this.OnNomePessoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="telefone", Storage="_TelefonePessoa", DbType="VarChar(30)")]
		public string TelefonePessoa
		{
			get
			{
				return this._TelefonePessoa;
			}
			set
			{
				if ((this._TelefonePessoa != value))
				{
					this.OnTelefonePessoaChanging(value);
					this.SendPropertyChanging();
					this._TelefonePessoa = value;
					this.SendPropertyChanged("TelefonePessoa");
					this.OnTelefonePessoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="email", Storage="_EmailPessoa", DbType="VarChar(200)")]
		public string EmailPessoa
		{
			get
			{
				return this._EmailPessoa;
			}
			set
			{
				if ((this._EmailPessoa != value))
				{
					this.OnEmailPessoaChanging(value);
					this.SendPropertyChanging();
					this._EmailPessoa = value;
					this.SendPropertyChanged("EmailPessoa");
					this.OnEmailPessoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblpessoa_tblPessoaFisica", Storage="_tblPessoaFisica", ThisKey="Codigopessoa", OtherKey="FKCodPessoa", IsUnique=true, IsForeignKey=false)]
		public tblPessoaFisica tblPessoaFisica
		{
			get
			{
				return this._tblPessoaFisica.Entity;
			}
			set
			{
				tblPessoaFisica previousValue = this._tblPessoaFisica.Entity;
				if (((previousValue != value) 
							|| (this._tblPessoaFisica.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblPessoaFisica.Entity = null;
						previousValue.tblpessoa = null;
					}
					this._tblPessoaFisica.Entity = value;
					if ((value != null))
					{
						value.tblpessoa = this;
					}
					this.SendPropertyChanged("tblPessoaFisica");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblpessoa_tblPessoaJuridica", Storage="_tblPessoaJuridica", ThisKey="Codigopessoa", OtherKey="FLCodPessoa", IsUnique=true, IsForeignKey=false)]
		public tblPessoaJuridica tblPessoaJuridica
		{
			get
			{
				return this._tblPessoaJuridica.Entity;
			}
			set
			{
				tblPessoaJuridica previousValue = this._tblPessoaJuridica.Entity;
				if (((previousValue != value) 
							|| (this._tblPessoaJuridica.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblPessoaJuridica.Entity = null;
						previousValue.tblpessoa = null;
					}
					this._tblPessoaJuridica.Entity = value;
					if ((value != null))
					{
						value.tblpessoa = this;
					}
					this.SendPropertyChanged("tblPessoaJuridica");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblpessoa_tblUsuario", Storage="_tblUsuario", ThisKey="Codigopessoa", OtherKey="FKCodPessoa", IsUnique=true, IsForeignKey=false)]
		public tblUsuario tblUsuario
		{
			get
			{
				return this._tblUsuario.Entity;
			}
			set
			{
				tblUsuario previousValue = this._tblUsuario.Entity;
				if (((previousValue != value) 
							|| (this._tblUsuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblUsuario.Entity = null;
						previousValue.tblpessoa = null;
					}
					this._tblUsuario.Entity = value;
					if ((value != null))
					{
						value.tblpessoa = this;
					}
					this.SendPropertyChanged("tblUsuario");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblpessoa_tb_venda", Storage="_tb_vendas", ThisKey="Codigopessoa", OtherKey="FKCodigoPessoa")]
		public EntitySet<tb_venda> tb_vendas
		{
			get
			{
				return this._tb_vendas;
			}
			set
			{
				this._tb_vendas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_vendas(tb_venda entity)
		{
			this.SendPropertyChanging();
			entity.tblpessoa = this;
		}
		
		private void detach_tb_vendas(tb_venda entity)
		{
			this.SendPropertyChanging();
			entity.tblpessoa = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_pessoa_fisica")]
	public partial class tblPessoaFisica : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CPF_PF;
		
		private string _RG_PF;
		
		private System.Nullable<System.DateTime> _DataNascPF;
		
		private string _PaiPF;
		
		private string _MaePF;
		
		private int _FKCodPessoa;
		
		private EntityRef<tblpessoa> _tblpessoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCPF_PFChanging(string value);
    partial void OnCPF_PFChanged();
    partial void OnRG_PFChanging(string value);
    partial void OnRG_PFChanged();
    partial void OnDataNascPFChanging(System.Nullable<System.DateTime> value);
    partial void OnDataNascPFChanged();
    partial void OnPaiPFChanging(string value);
    partial void OnPaiPFChanged();
    partial void OnMaePFChanging(string value);
    partial void OnMaePFChanged();
    partial void OnFKCodPessoaChanging(int value);
    partial void OnFKCodPessoaChanged();
    #endregion
		
		public tblPessoaFisica()
		{
			this._tblpessoa = default(EntityRef<tblpessoa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="cpf", Storage="_CPF_PF", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CPF_PF
		{
			get
			{
				return this._CPF_PF;
			}
			set
			{
				if ((this._CPF_PF != value))
				{
					this.OnCPF_PFChanging(value);
					this.SendPropertyChanging();
					this._CPF_PF = value;
					this.SendPropertyChanged("CPF_PF");
					this.OnCPF_PFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="rg", Storage="_RG_PF", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string RG_PF
		{
			get
			{
				return this._RG_PF;
			}
			set
			{
				if ((this._RG_PF != value))
				{
					this.OnRG_PFChanging(value);
					this.SendPropertyChanging();
					this._RG_PF = value;
					this.SendPropertyChanged("RG_PF");
					this.OnRG_PFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="data_nascimento", Storage="_DataNascPF", DbType="Date")]
		public System.Nullable<System.DateTime> DataNascPF
		{
			get
			{
				return this._DataNascPF;
			}
			set
			{
				if ((this._DataNascPF != value))
				{
					this.OnDataNascPFChanging(value);
					this.SendPropertyChanging();
					this._DataNascPF = value;
					this.SendPropertyChanged("DataNascPF");
					this.OnDataNascPFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="pai", Storage="_PaiPF", DbType="VarChar(200)")]
		public string PaiPF
		{
			get
			{
				return this._PaiPF;
			}
			set
			{
				if ((this._PaiPF != value))
				{
					this.OnPaiPFChanging(value);
					this.SendPropertyChanging();
					this._PaiPF = value;
					this.SendPropertyChanged("PaiPF");
					this.OnPaiPFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="mae", Storage="_MaePF", DbType="VarChar(200)")]
		public string MaePF
		{
			get
			{
				return this._MaePF;
			}
			set
			{
				if ((this._MaePF != value))
				{
					this.OnMaePFChanging(value);
					this.SendPropertyChanging();
					this._MaePF = value;
					this.SendPropertyChanged("MaePF");
					this.OnMaePFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_pessoa", Storage="_FKCodPessoa", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int FKCodPessoa
		{
			get
			{
				return this._FKCodPessoa;
			}
			set
			{
				if ((this._FKCodPessoa != value))
				{
					this.OnFKCodPessoaChanging(value);
					this.SendPropertyChanging();
					this._FKCodPessoa = value;
					this.SendPropertyChanged("FKCodPessoa");
					this.OnFKCodPessoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblpessoa_tblPessoaFisica", Storage="_tblpessoa", ThisKey="FKCodPessoa", OtherKey="Codigopessoa", IsForeignKey=true)]
		public tblpessoa tblpessoa
		{
			get
			{
				return this._tblpessoa.Entity;
			}
			set
			{
				tblpessoa previousValue = this._tblpessoa.Entity;
				if (((previousValue != value) 
							|| (this._tblpessoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblpessoa.Entity = null;
						previousValue.tblPessoaFisica = null;
					}
					this._tblpessoa.Entity = value;
					if ((value != null))
					{
						value.tblPessoaFisica = this;
						this._FKCodPessoa = value.Codigopessoa;
					}
					else
					{
						this._FKCodPessoa = default(int);
					}
					this.SendPropertyChanged("tblpessoa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_pessoa_juridica")]
	public partial class tblPessoaJuridica : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CNPJ_PF;
		
		private string _Inscricao_PF;
		
		private string _RazaoSocialPF;
		
		private int _FLCodPessoa;
		
		private EntityRef<tblpessoa> _tblpessoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCNPJ_PFChanging(string value);
    partial void OnCNPJ_PFChanged();
    partial void OnInscricao_PFChanging(string value);
    partial void OnInscricao_PFChanged();
    partial void OnRazaoSocialPFChanging(string value);
    partial void OnRazaoSocialPFChanged();
    partial void OnFLCodPessoaChanging(int value);
    partial void OnFLCodPessoaChanged();
    #endregion
		
		public tblPessoaJuridica()
		{
			this._tblpessoa = default(EntityRef<tblpessoa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="cnpj", Storage="_CNPJ_PF", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string CNPJ_PF
		{
			get
			{
				return this._CNPJ_PF;
			}
			set
			{
				if ((this._CNPJ_PF != value))
				{
					this.OnCNPJ_PFChanging(value);
					this.SendPropertyChanging();
					this._CNPJ_PF = value;
					this.SendPropertyChanged("CNPJ_PF");
					this.OnCNPJ_PFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="inscricao", Storage="_Inscricao_PF", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Inscricao_PF
		{
			get
			{
				return this._Inscricao_PF;
			}
			set
			{
				if ((this._Inscricao_PF != value))
				{
					this.OnInscricao_PFChanging(value);
					this.SendPropertyChanging();
					this._Inscricao_PF = value;
					this.SendPropertyChanged("Inscricao_PF");
					this.OnInscricao_PFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="razao_social", Storage="_RazaoSocialPF", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string RazaoSocialPF
		{
			get
			{
				return this._RazaoSocialPF;
			}
			set
			{
				if ((this._RazaoSocialPF != value))
				{
					this.OnRazaoSocialPFChanging(value);
					this.SendPropertyChanging();
					this._RazaoSocialPF = value;
					this.SendPropertyChanged("RazaoSocialPF");
					this.OnRazaoSocialPFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_pessoa", Storage="_FLCodPessoa", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int FLCodPessoa
		{
			get
			{
				return this._FLCodPessoa;
			}
			set
			{
				if ((this._FLCodPessoa != value))
				{
					this.OnFLCodPessoaChanging(value);
					this.SendPropertyChanging();
					this._FLCodPessoa = value;
					this.SendPropertyChanged("FLCodPessoa");
					this.OnFLCodPessoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblpessoa_tblPessoaJuridica", Storage="_tblpessoa", ThisKey="FLCodPessoa", OtherKey="Codigopessoa", IsForeignKey=true)]
		public tblpessoa tblpessoa
		{
			get
			{
				return this._tblpessoa.Entity;
			}
			set
			{
				tblpessoa previousValue = this._tblpessoa.Entity;
				if (((previousValue != value) 
							|| (this._tblpessoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblpessoa.Entity = null;
						previousValue.tblPessoaJuridica = null;
					}
					this._tblpessoa.Entity = value;
					if ((value != null))
					{
						value.tblPessoaJuridica = this;
						this._FLCodPessoa = value.Codigopessoa;
					}
					else
					{
						this._FLCodPessoa = default(int);
					}
					this.SendPropertyChanged("tblpessoa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_usuario")]
	public partial class tblUsuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _NomeUsuario;
		
		private string _SenhaUsuario;
		
		private int _FKCodPessoa;
		
		private EntityRef<tblpessoa> _tblpessoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNomeUsuarioChanging(string value);
    partial void OnNomeUsuarioChanged();
    partial void OnSenhaUsuarioChanging(string value);
    partial void OnSenhaUsuarioChanged();
    partial void OnFKCodPessoaChanging(int value);
    partial void OnFKCodPessoaChanged();
    #endregion
		
		public tblUsuario()
		{
			this._tblpessoa = default(EntityRef<tblpessoa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="usuario", Storage="_NomeUsuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NomeUsuario
		{
			get
			{
				return this._NomeUsuario;
			}
			set
			{
				if ((this._NomeUsuario != value))
				{
					this.OnNomeUsuarioChanging(value);
					this.SendPropertyChanging();
					this._NomeUsuario = value;
					this.SendPropertyChanged("NomeUsuario");
					this.OnNomeUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="senha", Storage="_SenhaUsuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string SenhaUsuario
		{
			get
			{
				return this._SenhaUsuario;
			}
			set
			{
				if ((this._SenhaUsuario != value))
				{
					this.OnSenhaUsuarioChanging(value);
					this.SendPropertyChanging();
					this._SenhaUsuario = value;
					this.SendPropertyChanged("SenhaUsuario");
					this.OnSenhaUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_pessoa", Storage="_FKCodPessoa", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int FKCodPessoa
		{
			get
			{
				return this._FKCodPessoa;
			}
			set
			{
				if ((this._FKCodPessoa != value))
				{
					this.OnFKCodPessoaChanging(value);
					this.SendPropertyChanging();
					this._FKCodPessoa = value;
					this.SendPropertyChanged("FKCodPessoa");
					this.OnFKCodPessoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblpessoa_tblUsuario", Storage="_tblpessoa", ThisKey="FKCodPessoa", OtherKey="Codigopessoa", IsForeignKey=true)]
		public tblpessoa tblpessoa
		{
			get
			{
				return this._tblpessoa.Entity;
			}
			set
			{
				tblpessoa previousValue = this._tblpessoa.Entity;
				if (((previousValue != value) 
							|| (this._tblpessoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblpessoa.Entity = null;
						previousValue.tblUsuario = null;
					}
					this._tblpessoa.Entity = value;
					if ((value != null))
					{
						value.tblUsuario = this;
						this._FKCodPessoa = value.Codigopessoa;
					}
					else
					{
						this._FKCodPessoa = default(int);
					}
					this.SendPropertyChanged("tblpessoa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_venda")]
	public partial class tb_venda : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodigoVenda;
		
		private System.Nullable<decimal> _ValorVenda;
		
		private System.Nullable<decimal> _DescontoVenda;
		
		private System.Nullable<decimal> _ValorPagoVenda;
		
		private System.Nullable<int> _FKCodigoPessoa;
		
		private EntitySet<tb_itens_venda> _tb_itens_vendas;
		
		private EntitySet<tb_contas_receber> _tb_contas_recebers;
		
		private EntityRef<tblpessoa> _tblpessoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoVendaChanging(int value);
    partial void OnCodigoVendaChanged();
    partial void OnValorVendaChanging(System.Nullable<decimal> value);
    partial void OnValorVendaChanged();
    partial void OnDescontoVendaChanging(System.Nullable<decimal> value);
    partial void OnDescontoVendaChanged();
    partial void OnValorPagoVendaChanging(System.Nullable<decimal> value);
    partial void OnValorPagoVendaChanged();
    partial void OnFKCodigoPessoaChanging(System.Nullable<int> value);
    partial void OnFKCodigoPessoaChanged();
    #endregion
		
		public tb_venda()
		{
			this._tb_itens_vendas = new EntitySet<tb_itens_venda>(new Action<tb_itens_venda>(this.attach_tb_itens_vendas), new Action<tb_itens_venda>(this.detach_tb_itens_vendas));
			this._tb_contas_recebers = new EntitySet<tb_contas_receber>(new Action<tb_contas_receber>(this.attach_tb_contas_recebers), new Action<tb_contas_receber>(this.detach_tb_contas_recebers));
			this._tblpessoa = default(EntityRef<tblpessoa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_venda", Storage="_CodigoVenda", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodigoVenda
		{
			get
			{
				return this._CodigoVenda;
			}
			set
			{
				if ((this._CodigoVenda != value))
				{
					this.OnCodigoVendaChanging(value);
					this.SendPropertyChanging();
					this._CodigoVenda = value;
					this.SendPropertyChanged("CodigoVenda");
					this.OnCodigoVendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="valor", Storage="_ValorVenda", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> ValorVenda
		{
			get
			{
				return this._ValorVenda;
			}
			set
			{
				if ((this._ValorVenda != value))
				{
					this.OnValorVendaChanging(value);
					this.SendPropertyChanging();
					this._ValorVenda = value;
					this.SendPropertyChanged("ValorVenda");
					this.OnValorVendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="desconto", Storage="_DescontoVenda", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> DescontoVenda
		{
			get
			{
				return this._DescontoVenda;
			}
			set
			{
				if ((this._DescontoVenda != value))
				{
					this.OnDescontoVendaChanging(value);
					this.SendPropertyChanging();
					this._DescontoVenda = value;
					this.SendPropertyChanged("DescontoVenda");
					this.OnDescontoVendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="valor_pago", Storage="_ValorPagoVenda", DbType="Decimal(15,2)")]
		public System.Nullable<decimal> ValorPagoVenda
		{
			get
			{
				return this._ValorPagoVenda;
			}
			set
			{
				if ((this._ValorPagoVenda != value))
				{
					this.OnValorPagoVendaChanging(value);
					this.SendPropertyChanging();
					this._ValorPagoVenda = value;
					this.SendPropertyChanged("ValorPagoVenda");
					this.OnValorPagoVendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_pessoa", Storage="_FKCodigoPessoa", DbType="Int")]
		public System.Nullable<int> FKCodigoPessoa
		{
			get
			{
				return this._FKCodigoPessoa;
			}
			set
			{
				if ((this._FKCodigoPessoa != value))
				{
					this.OnFKCodigoPessoaChanging(value);
					this.SendPropertyChanging();
					this._FKCodigoPessoa = value;
					this.SendPropertyChanged("FKCodigoPessoa");
					this.OnFKCodigoPessoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_venda_tb_itens_venda", Storage="_tb_itens_vendas", ThisKey="CodigoVenda", OtherKey="FKCodigovenda")]
		public EntitySet<tb_itens_venda> tb_itens_vendas
		{
			get
			{
				return this._tb_itens_vendas;
			}
			set
			{
				this._tb_itens_vendas.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_venda_tb_contas_receber", Storage="_tb_contas_recebers", ThisKey="CodigoVenda", OtherKey="FkCodigoVenda")]
		public EntitySet<tb_contas_receber> tb_contas_recebers
		{
			get
			{
				return this._tb_contas_recebers;
			}
			set
			{
				this._tb_contas_recebers.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblpessoa_tb_venda", Storage="_tblpessoa", ThisKey="FKCodigoPessoa", OtherKey="Codigopessoa", IsForeignKey=true)]
		public tblpessoa tblpessoa
		{
			get
			{
				return this._tblpessoa.Entity;
			}
			set
			{
				tblpessoa previousValue = this._tblpessoa.Entity;
				if (((previousValue != value) 
							|| (this._tblpessoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblpessoa.Entity = null;
						previousValue.tb_vendas.Remove(this);
					}
					this._tblpessoa.Entity = value;
					if ((value != null))
					{
						value.tb_vendas.Add(this);
						this._FKCodigoPessoa = value.Codigopessoa;
					}
					else
					{
						this._FKCodigoPessoa = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblpessoa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_itens_vendas(tb_itens_venda entity)
		{
			this.SendPropertyChanging();
			entity.tb_venda = this;
		}
		
		private void detach_tb_itens_vendas(tb_itens_venda entity)
		{
			this.SendPropertyChanging();
			entity.tb_venda = null;
		}
		
		private void attach_tb_contas_recebers(tb_contas_receber entity)
		{
			this.SendPropertyChanging();
			entity.tb_venda = this;
		}
		
		private void detach_tb_contas_recebers(tb_contas_receber entity)
		{
			this.SendPropertyChanging();
			entity.tb_venda = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_itens_venda")]
	public partial class tb_itens_venda : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Quantidade;
		
		private int _FKCodigoproduto;
		
		private int _FKCodigovenda;
		
		private decimal _ValorItemVenda;
		
		private int _CodigoitemVenda;
		
		private EntityRef<tblProduto> _tblProduto;
		
		private EntityRef<tb_venda> _tb_venda;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnQuantidadeChanging(int value);
    partial void OnQuantidadeChanged();
    partial void OnFKCodigoprodutoChanging(int value);
    partial void OnFKCodigoprodutoChanged();
    partial void OnFKCodigovendaChanging(int value);
    partial void OnFKCodigovendaChanged();
    partial void OnValorItemVendaChanging(decimal value);
    partial void OnValorItemVendaChanged();
    partial void OnCodigoitemVendaChanging(int value);
    partial void OnCodigoitemVendaChanged();
    #endregion
		
		public tb_itens_venda()
		{
			this._tblProduto = default(EntityRef<tblProduto>);
			this._tb_venda = default(EntityRef<tb_venda>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="quantidade", Storage="_Quantidade", DbType="Int NOT NULL")]
		public int Quantidade
		{
			get
			{
				return this._Quantidade;
			}
			set
			{
				if ((this._Quantidade != value))
				{
					this.OnQuantidadeChanging(value);
					this.SendPropertyChanging();
					this._Quantidade = value;
					this.SendPropertyChanged("Quantidade");
					this.OnQuantidadeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_produto", Storage="_FKCodigoproduto", DbType="Int NOT NULL")]
		public int FKCodigoproduto
		{
			get
			{
				return this._FKCodigoproduto;
			}
			set
			{
				if ((this._FKCodigoproduto != value))
				{
					this.OnFKCodigoprodutoChanging(value);
					this.SendPropertyChanging();
					this._FKCodigoproduto = value;
					this.SendPropertyChanged("FKCodigoproduto");
					this.OnFKCodigoprodutoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_venda", Storage="_FKCodigovenda", DbType="Int NOT NULL")]
		public int FKCodigovenda
		{
			get
			{
				return this._FKCodigovenda;
			}
			set
			{
				if ((this._FKCodigovenda != value))
				{
					this.OnFKCodigovendaChanging(value);
					this.SendPropertyChanging();
					this._FKCodigovenda = value;
					this.SendPropertyChanged("FKCodigovenda");
					this.OnFKCodigovendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="valor", Storage="_ValorItemVenda", DbType="Decimal(15,2) NOT NULL")]
		public decimal ValorItemVenda
		{
			get
			{
				return this._ValorItemVenda;
			}
			set
			{
				if ((this._ValorItemVenda != value))
				{
					this.OnValorItemVendaChanging(value);
					this.SendPropertyChanging();
					this._ValorItemVenda = value;
					this.SendPropertyChanged("ValorItemVenda");
					this.OnValorItemVendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_item", Storage="_CodigoitemVenda", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodigoitemVenda
		{
			get
			{
				return this._CodigoitemVenda;
			}
			set
			{
				if ((this._CodigoitemVenda != value))
				{
					this.OnCodigoitemVendaChanging(value);
					this.SendPropertyChanging();
					this._CodigoitemVenda = value;
					this.SendPropertyChanged("CodigoitemVenda");
					this.OnCodigoitemVendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblProduto_tb_itens_venda", Storage="_tblProduto", ThisKey="FKCodigoproduto", OtherKey="CodigoProduto", IsForeignKey=true)]
		public tblProduto tblProduto
		{
			get
			{
				return this._tblProduto.Entity;
			}
			set
			{
				tblProduto previousValue = this._tblProduto.Entity;
				if (((previousValue != value) 
							|| (this._tblProduto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblProduto.Entity = null;
						previousValue.tb_itens_vendas.Remove(this);
					}
					this._tblProduto.Entity = value;
					if ((value != null))
					{
						value.tb_itens_vendas.Add(this);
						this._FKCodigoproduto = value.CodigoProduto;
					}
					else
					{
						this._FKCodigoproduto = default(int);
					}
					this.SendPropertyChanged("tblProduto");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_venda_tb_itens_venda", Storage="_tb_venda", ThisKey="FKCodigovenda", OtherKey="CodigoVenda", IsForeignKey=true)]
		public tb_venda tb_venda
		{
			get
			{
				return this._tb_venda.Entity;
			}
			set
			{
				tb_venda previousValue = this._tb_venda.Entity;
				if (((previousValue != value) 
							|| (this._tb_venda.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_venda.Entity = null;
						previousValue.tb_itens_vendas.Remove(this);
					}
					this._tb_venda.Entity = value;
					if ((value != null))
					{
						value.tb_itens_vendas.Add(this);
						this._FKCodigovenda = value.CodigoVenda;
					}
					else
					{
						this._FKCodigovenda = default(int);
					}
					this.SendPropertyChanged("tb_venda");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_status_pagamento")]
	public partial class tb_status_pagamento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodigoStatus;
		
		private string _NomesDoStatus;
		
		private EntitySet<tb_contas_receber> _tb_contas_recebers;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoStatusChanging(int value);
    partial void OnCodigoStatusChanged();
    partial void OnNomesDoStatusChanging(string value);
    partial void OnNomesDoStatusChanged();
    #endregion
		
		public tb_status_pagamento()
		{
			this._tb_contas_recebers = new EntitySet<tb_contas_receber>(new Action<tb_contas_receber>(this.attach_tb_contas_recebers), new Action<tb_contas_receber>(this.detach_tb_contas_recebers));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_status", Storage="_CodigoStatus", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodigoStatus
		{
			get
			{
				return this._CodigoStatus;
			}
			set
			{
				if ((this._CodigoStatus != value))
				{
					this.OnCodigoStatusChanging(value);
					this.SendPropertyChanging();
					this._CodigoStatus = value;
					this.SendPropertyChanged("CodigoStatus");
					this.OnCodigoStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="status", Storage="_NomesDoStatus", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NomesDoStatus
		{
			get
			{
				return this._NomesDoStatus;
			}
			set
			{
				if ((this._NomesDoStatus != value))
				{
					this.OnNomesDoStatusChanging(value);
					this.SendPropertyChanging();
					this._NomesDoStatus = value;
					this.SendPropertyChanged("NomesDoStatus");
					this.OnNomesDoStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_status_pagamento_tb_contas_receber", Storage="_tb_contas_recebers", ThisKey="CodigoStatus", OtherKey="FKStatusPagamento")]
		public EntitySet<tb_contas_receber> tb_contas_recebers
		{
			get
			{
				return this._tb_contas_recebers;
			}
			set
			{
				this._tb_contas_recebers.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_contas_recebers(tb_contas_receber entity)
		{
			this.SendPropertyChanging();
			entity.tb_status_pagamento = this;
		}
		
		private void detach_tb_contas_recebers(tb_contas_receber entity)
		{
			this.SendPropertyChanging();
			entity.tb_status_pagamento = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_contas_receber")]
	public partial class tb_contas_receber : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CodigoConta;
		
		private System.DateTime _DataDaCompra;
		
		private System.DateTime _DataDeVencimento;
		
		private System.Nullable<System.DateTime> _DataDePagamento;
		
		private int _FkCodigoVenda;
		
		private int _FKStatusPagamento;
		
		private EntityRef<tb_venda> _tb_venda;
		
		private EntityRef<tb_status_pagamento> _tb_status_pagamento;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCodigoContaChanging(int value);
    partial void OnCodigoContaChanged();
    partial void OnDataDaCompraChanging(System.DateTime value);
    partial void OnDataDaCompraChanged();
    partial void OnDataDeVencimentoChanging(System.DateTime value);
    partial void OnDataDeVencimentoChanged();
    partial void OnDataDePagamentoChanging(System.Nullable<System.DateTime> value);
    partial void OnDataDePagamentoChanged();
    partial void OnFkCodigoVendaChanging(int value);
    partial void OnFkCodigoVendaChanged();
    partial void OnFKStatusPagamentoChanging(int value);
    partial void OnFKStatusPagamentoChanged();
    #endregion
		
		public tb_contas_receber()
		{
			this._tb_venda = default(EntityRef<tb_venda>);
			this._tb_status_pagamento = default(EntityRef<tb_status_pagamento>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_conta", Storage="_CodigoConta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CodigoConta
		{
			get
			{
				return this._CodigoConta;
			}
			set
			{
				if ((this._CodigoConta != value))
				{
					this.OnCodigoContaChanging(value);
					this.SendPropertyChanging();
					this._CodigoConta = value;
					this.SendPropertyChanged("CodigoConta");
					this.OnCodigoContaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="data_compra", Storage="_DataDaCompra", DbType="Date NOT NULL")]
		public System.DateTime DataDaCompra
		{
			get
			{
				return this._DataDaCompra;
			}
			set
			{
				if ((this._DataDaCompra != value))
				{
					this.OnDataDaCompraChanging(value);
					this.SendPropertyChanging();
					this._DataDaCompra = value;
					this.SendPropertyChanged("DataDaCompra");
					this.OnDataDaCompraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="data_vencimento", Storage="_DataDeVencimento", DbType="Date NOT NULL")]
		public System.DateTime DataDeVencimento
		{
			get
			{
				return this._DataDeVencimento;
			}
			set
			{
				if ((this._DataDeVencimento != value))
				{
					this.OnDataDeVencimentoChanging(value);
					this.SendPropertyChanging();
					this._DataDeVencimento = value;
					this.SendPropertyChanged("DataDeVencimento");
					this.OnDataDeVencimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="data_pagamento", Storage="_DataDePagamento", DbType="Date")]
		public System.Nullable<System.DateTime> DataDePagamento
		{
			get
			{
				return this._DataDePagamento;
			}
			set
			{
				if ((this._DataDePagamento != value))
				{
					this.OnDataDePagamentoChanging(value);
					this.SendPropertyChanging();
					this._DataDePagamento = value;
					this.SendPropertyChanged("DataDePagamento");
					this.OnDataDePagamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_venda", Storage="_FkCodigoVenda", DbType="Int NOT NULL")]
		public int FkCodigoVenda
		{
			get
			{
				return this._FkCodigoVenda;
			}
			set
			{
				if ((this._FkCodigoVenda != value))
				{
					this.OnFkCodigoVendaChanging(value);
					this.SendPropertyChanging();
					this._FkCodigoVenda = value;
					this.SendPropertyChanged("FkCodigoVenda");
					this.OnFkCodigoVendaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="id_status", Storage="_FKStatusPagamento", DbType="Int NOT NULL")]
		public int FKStatusPagamento
		{
			get
			{
				return this._FKStatusPagamento;
			}
			set
			{
				if ((this._FKStatusPagamento != value))
				{
					this.OnFKStatusPagamentoChanging(value);
					this.SendPropertyChanging();
					this._FKStatusPagamento = value;
					this.SendPropertyChanged("FKStatusPagamento");
					this.OnFKStatusPagamentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_venda_tb_contas_receber", Storage="_tb_venda", ThisKey="FkCodigoVenda", OtherKey="CodigoVenda", IsForeignKey=true)]
		public tb_venda tb_venda
		{
			get
			{
				return this._tb_venda.Entity;
			}
			set
			{
				tb_venda previousValue = this._tb_venda.Entity;
				if (((previousValue != value) 
							|| (this._tb_venda.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_venda.Entity = null;
						previousValue.tb_contas_recebers.Remove(this);
					}
					this._tb_venda.Entity = value;
					if ((value != null))
					{
						value.tb_contas_recebers.Add(this);
						this._FkCodigoVenda = value.CodigoVenda;
					}
					else
					{
						this._FkCodigoVenda = default(int);
					}
					this.SendPropertyChanged("tb_venda");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_status_pagamento_tb_contas_receber", Storage="_tb_status_pagamento", ThisKey="FKStatusPagamento", OtherKey="CodigoStatus", IsForeignKey=true)]
		public tb_status_pagamento tb_status_pagamento
		{
			get
			{
				return this._tb_status_pagamento.Entity;
			}
			set
			{
				tb_status_pagamento previousValue = this._tb_status_pagamento.Entity;
				if (((previousValue != value) 
							|| (this._tb_status_pagamento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_status_pagamento.Entity = null;
						previousValue.tb_contas_recebers.Remove(this);
					}
					this._tb_status_pagamento.Entity = value;
					if ((value != null))
					{
						value.tb_contas_recebers.Add(this);
						this._FKStatusPagamento = value.CodigoStatus;
					}
					else
					{
						this._FKStatusPagamento = default(int);
					}
					this.SendPropertyChanged("tb_status_pagamento");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
